const ShopActionTypes = {
    FETCHE_COLLECTIONS_START: 'UPDATE_COLLECTIONS_START',
    FETCHE_COLLECTIONS_SUCCESS: 'FETCHE_COLLECTIONS_SUCCESS',
    FETCHE_COLLECTIONS_FAILURE: 'UPDATE_COLLECTIONS_FAILURE',
};
  
export default ShopActionTypes;